/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-07-24 at 03:20:03 UTC 
 * Modify at your own risk.
 */

package com.rafali.flickruploader.rpcendpoint;

/**
 * Service definition for Rpcendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link RpcendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Rpcendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ra-fa-li.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "rpcendpoint/v1/sendMail/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Rpcendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Rpcendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "sendMail".
   *
   * This request holds the parameters needed by the the rpcendpoint server.  After setting any
   * optional parameters, call the {@link SendMail#execute()} method to invoke the remote operation.
   *
   * @param recipient
   * @param subject
   * @param bodyHtml
   * @param fromAddress
   * @return the request
   */
  public SendMail sendMail(java.lang.String recipient, java.lang.String subject, java.lang.String bodyHtml, java.lang.String fromAddress) throws java.io.IOException {
    SendMail result = new SendMail(recipient, subject, bodyHtml, fromAddress);
    initialize(result);
    return result;
  }

  public class SendMail extends RpcendpointRequest<Void> {

    private static final String REST_PATH = "{recipient}/{subject}/{bodyHtml}/{fromAddress}";

    /**
     * Create a request for the method "sendMail".
     *
     * This request holds the parameters needed by the the rpcendpoint server.  After setting any
     * optional parameters, call the {@link SendMail#execute()} method to invoke the remote operation.
     * <p> {@link
     * SendMail#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param recipient
     * @param subject
     * @param bodyHtml
     * @param fromAddress
     * @since 1.13
     */
    protected SendMail(java.lang.String recipient, java.lang.String subject, java.lang.String bodyHtml, java.lang.String fromAddress) {
      super(Rpcendpoint.this, "POST", REST_PATH, null, Void.class);
      this.recipient = com.google.api.client.util.Preconditions.checkNotNull(recipient, "Required parameter recipient must be specified.");
      this.subject = com.google.api.client.util.Preconditions.checkNotNull(subject, "Required parameter subject must be specified.");
      this.bodyHtml = com.google.api.client.util.Preconditions.checkNotNull(bodyHtml, "Required parameter bodyHtml must be specified.");
      this.fromAddress = com.google.api.client.util.Preconditions.checkNotNull(fromAddress, "Required parameter fromAddress must be specified.");
    }

    @Override
    public SendMail setAlt(java.lang.String alt) {
      return (SendMail) super.setAlt(alt);
    }

    @Override
    public SendMail setFields(java.lang.String fields) {
      return (SendMail) super.setFields(fields);
    }

    @Override
    public SendMail setKey(java.lang.String key) {
      return (SendMail) super.setKey(key);
    }

    @Override
    public SendMail setOauthToken(java.lang.String oauthToken) {
      return (SendMail) super.setOauthToken(oauthToken);
    }

    @Override
    public SendMail setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SendMail) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SendMail setQuotaUser(java.lang.String quotaUser) {
      return (SendMail) super.setQuotaUser(quotaUser);
    }

    @Override
    public SendMail setUserIp(java.lang.String userIp) {
      return (SendMail) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String recipient;

    /**

     */
    public java.lang.String getRecipient() {
      return recipient;
    }

    public SendMail setRecipient(java.lang.String recipient) {
      this.recipient = recipient;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String subject;

    /**

     */
    public java.lang.String getSubject() {
      return subject;
    }

    public SendMail setSubject(java.lang.String subject) {
      this.subject = subject;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String bodyHtml;

    /**

     */
    public java.lang.String getBodyHtml() {
      return bodyHtml;
    }

    public SendMail setBodyHtml(java.lang.String bodyHtml) {
      this.bodyHtml = bodyHtml;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String fromAddress;

    /**

     */
    public java.lang.String getFromAddress() {
      return fromAddress;
    }

    public SendMail setFromAddress(java.lang.String fromAddress) {
      this.fromAddress = fromAddress;
      return this;
    }

    @Override
    public SendMail set(String parameterName, Object value) {
      return (SendMail) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Rpcendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Rpcendpoint}. */
    @Override
    public Rpcendpoint build() {
      return new Rpcendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link RpcendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setRpcendpointRequestInitializer(
        RpcendpointRequestInitializer rpcendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(rpcendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
