//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.rafali.flickruploader.ui;

import java.util.List;
import android.content.Context;
import android.os.Handler;
import android.os.Looper;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.rafali.flickruploader.model.Media;
import com.rafali.flickruploader.ui.DrawerContentView.PhotoAdapter;
import com.rafali.flickruploader2.R.id;
import com.rafali.flickruploader2.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class DrawerContentView_
    extends DrawerContentView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    public DrawerContentView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public static DrawerContentView build(Context context, AttributeSet attrs) {
        DrawerContentView_ instance = new DrawerContentView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.drawer_content, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        pauseBtn = ((TextView) hasViews.findViewById(id.pause_btn));
        container = ((LinearLayout) hasViews.findViewById(id.container));
        clearBtn = ((TextView) hasViews.findViewById(id.clear_btn));
        {
            View view = hasViews.findViewById(id.clear_btn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DrawerContentView_.this.onClearClick();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.pause_btn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DrawerContentView_.this.onPauseClick();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.bottom_bar);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DrawerContentView_.this.onBottomBarClick();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void renderButtons() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                DrawerContentView_.super.renderButtons();
            }

        }
        );
    }

    @Override
    public void renderCurrentView() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                DrawerContentView_.super.renderCurrentView();
            }

        }
        );
    }

    @Override
    public void notifyDataSetChanged(final PhotoAdapter photoAdapter, final List<Media> medias) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                DrawerContentView_.super.notifyDataSetChanged(photoAdapter, medias);
            }

        }
        );
    }

}
