//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.rafali.flickruploader.ui.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ListView;
import android.widget.TextView;
import com.rafali.flickruploader.model.Folder;
import com.rafali.flickruploader2.R.id;
import com.rafali.flickruploader2.R.layout;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class AutoUploadFoldersActivity_
    extends AutoUploadFoldersActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.auto_upload_folders_activity);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static AutoUploadFoldersActivity_.IntentBuilder_ intent(Context context) {
        return new AutoUploadFoldersActivity_.IntentBuilder_(context);
    }

    public static AutoUploadFoldersActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new AutoUploadFoldersActivity_.IntentBuilder_(fragment);
    }

    public static AutoUploadFoldersActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new AutoUploadFoldersActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        loading = ((TextView) hasViews.findViewById(id.loading));
        listView = ((ListView) hasViews.findViewById(id.list_view));
    }

    @Override
    public void hideLoading() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                AutoUploadFoldersActivity_.super.hideLoading();
            }

        }
        );
    }

    @Override
    public void refresh() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                AutoUploadFoldersActivity_.super.refresh();
            }

        }
        );
    }

    @Override
    public void showLoading(final String title, final String message) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                AutoUploadFoldersActivity_.super.showLoading(title, message);
            }

        }
        );
    }

    @Override
    public void render() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                AutoUploadFoldersActivity_.super.render();
            }

        }
        );
    }

    @Override
    public void setAutoUploaded(final Folder folder, final String setTitle) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    AutoUploadFoldersActivity_.super.setAutoUploaded(folder, setTitle);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void load() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    AutoUploadFoldersActivity_.super.load();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, AutoUploadFoldersActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, AutoUploadFoldersActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, AutoUploadFoldersActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public AutoUploadFoldersActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
