//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.rafali.flickruploader.ui.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import com.rafali.flickruploader2.R.id;
import com.rafali.flickruploader2.R.layout;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class FlickrWebAuthActivity_
    extends FlickrWebAuthActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.flickr_web_auth_activity);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static FlickrWebAuthActivity_.IntentBuilder_ intent(Context context) {
        return new FlickrWebAuthActivity_.IntentBuilder_(context);
    }

    public static FlickrWebAuthActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new FlickrWebAuthActivity_.IntentBuilder_(fragment);
    }

    public static FlickrWebAuthActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new FlickrWebAuthActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        errorText = ((TextView) hasViews.findViewById(id.error_text));
        progressText = ((TextView) hasViews.findViewById(id.progress_text));
        progressContainer = ((View) hasViews.findViewById(id.progress_container));
        errorContainer = ((View) hasViews.findViewById(id.error_container));
        {
            View view = hasViews.findViewById(id.error_button);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        FlickrWebAuthActivity_.this.onErrorClick();
                    }

                }
                );
            }
        }
        onAfterViews();
    }

    @Override
    public void setLoading(final String message) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                FlickrWebAuthActivity_.super.setLoading(message);
            }

        }
        );
    }

    @Override
    public void setError(final java.lang.Throwable e) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                FlickrWebAuthActivity_.super.setError(e);
            }

        }
        );
    }

    @Override
    public void loadAuthorizationUrl() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    FlickrWebAuthActivity_.super.loadAuthorizationUrl();
                } catch (java.lang.Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void doDataCallback() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    FlickrWebAuthActivity_.super.doDataCallback();
                } catch (java.lang.Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, FlickrWebAuthActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, FlickrWebAuthActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, FlickrWebAuthActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public FlickrWebAuthActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
